name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
    
    - name: Build Windows executable
      run: |
        python -m PyInstaller --onefile --windowed --name="朗润播放器客户端_独立版" 朗润播放器客户端_独立版.py
    
    - name: Create release package
      run: |
        mkdir "朗润播放器客户端_独立版_Windows发布包"
        copy "dist\朗润播放器客户端_独立版.exe" "朗润播放器客户端_独立版_Windows发布包\"
        
        echo @echo off > "朗润播放器客户端_独立版_Windows发布包\启动朗润播放器.bat"
        echo chcp 65001 ^> nul >> "朗润播放器客户端_独立版_Windows发布包\启动朗润播放器.bat"
        echo echo 正在启动朗润播放器客户端... >> "朗润播放器客户端_独立版_Windows发布包\启动朗润播放器.bat"
        echo "朗润播放器客户端_独立版.exe" >> "朗润播放器客户端_独立版_Windows发布包\启动朗润播放器.bat"
        echo pause >> "朗润播放器客户端_独立版_Windows发布包\启动朗润播放器.bat"
        
        echo 展演号码,姓名,作品名称,媒体链接 > "朗润播放器客户端_独立版_Windows发布包\数据模板.csv"
        echo 001,张三,春天的故事,http://example.com/media1.mp3 >> "朗润播放器客户端_独立版_Windows发布包\数据模板.csv"
        
        mkdir "朗润播放器客户端_独立版_Windows发布包\downloaded_media"
    
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: 朗润播放器客户端_独立版_Windows
        path: 朗润播放器客户端_独立版_Windows发布包/
    
    - name: Create ZIP package
      run: |
        powershell Compress-Archive -Path "朗润播放器客户端_独立版_Windows发布包" -DestinationPath "朗润播放器客户端_独立版_Windows_v1.0.zip"
    
    - name: Upload ZIP package
      uses: actions/upload-artifact@v4
      with:
        name: 朗润播放器客户端_独立版_Windows_ZIP
        path: 朗润播放器客户端_独立版_Windows_v1.0.zip 
        
